---
title: "EDA"
author: "John Reisner"
date: "April 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'center', message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
land <- read.csv("Global_Landslide_Catalog_Export.csv")
```
## Count of Landslides
### Trigger
```{r}
land %>%
  group_by(landslide_trigger) %>%
  tally() %>%
  arrange(n) %>%
  mutate(landslide_trigger = factor(landslide_trigger, levels = landslide_trigger)) %>%
  ggplot(aes(x = landslide_trigger, y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### Size
```{r}
land %>%
  group_by(landslide_size) %>%
  tally() %>%
  arrange(n) %>%
  mutate(landslide_size = factor(landslide_size, levels = landslide_size)) %>%
  ggplot(aes(x = landslide_size, y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### Type
```{r}
land %>%
  group_by(landslide_category) %>%
  tally() %>%
  ggplot(aes(x = reorder(landslide_category, n, median), y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### Landslides in each country
```{r}
land %>%
  group_by(country_name) %>%
  tally() %>%
  arrange(n) %>%
  mutate(country_name = factor(country_name, levels = country_name)) %>%
  top_n(25) %>%
  ggplot(aes(x = country_name, y = n)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```


## Total Fatalities

### Trigger
```{r}
land %>%
  group_by(landslide_trigger) %>%
  summarise(Deaths = sum(fatality_count, na.rm = TRUE)) %>%
  arrange(Deaths) %>%
  mutate(landslide_trigger = factor(landslide_trigger, levels = landslide_trigger)) %>%
  ggplot(aes(x = landslide_trigger, y = Deaths)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### Size
```{r}
land %>%
  group_by(landslide_size) %>%
  summarise(Deaths = sum(fatality_count, na.rm = TRUE)) %>%
  arrange(Deaths) %>%
  mutate(landslide_size = factor(landslide_size, levels = landslide_size)) %>%
  ggplot(aes(x = landslide_size, y = Deaths)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### Type
```{r}
land %>%
  group_by(landslide_category) %>%
  summarise(Deaths = sum(fatality_count, na.rm = TRUE)) %>%
  ggplot(aes(x = reorder(landslide_category, Deaths, median), y = Deaths)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

### In each country
```{r}
land %>%
  group_by(country_name) %>%
  summarise(Deaths = sum(fatality_count, na.rm = TRUE)) %>%
  arrange(Deaths) %>%
  mutate(country_name = factor(country_name, levels = country_name)) %>%
  top_n(25) %>%
  ggplot(aes(x = country_name, y = Deaths)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```



### Mean fatalities per country
```{r}
land %>%
  group_by(country_name) %>%
  summarise(Fatals = mean(fatality_count, na.rm = TRUE)) %>%
  arrange(Fatals) %>%
  mutate(country_name = factor(country_name, levels = country_name)) %>%
  top_n(25) %>%
  ggplot(aes(x = country_name, y = Fatals)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  theme_bw()
```

